### ISSUE TITLE
Add custom filters to the KafkaIasiosConsumer

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias#133]
Currently the KakfaCoreConsumer allows to add filters by type of iasio and by ID and the filters work with AND. It would be useful to filter using custom filters, for example, a filter with an OR between type and ID.

**Comment by acaproni** [comment]
Implemented  providing [FilteredKafkaIasiosConsumer](https://github.com/IntegratedAlarmSystem-Group/ias/blob/develop/KafkaUtils/src/main/java/org/eso/ias/kafkautils/FilteredKafkaIasiosConsumer.java).

Objects of this class accept a filter to accept or reject `IASValue`s.
