### ISSUE TITLE
WebServerSender exception

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#136]
This morning the IAS web server shows all alarms invalid.
The weather plugin on ias-server01 runs and some of the monitor points are RELIABLE:

```
>iasDumpKafkaTopic -t core|grep RELIABLE|grep -v UNRELIABLE
{"value":"9.4","readFromMonSysTStamp":"2018-10-16T12:05:26.300","pluginProductionTStamp":"2018-10-16T12:05:26.755","sentToConverterTStamp":"2018-10-16T12:05:26.755","receivedFromPluginTStamp":"2018-10-16T12:05:26.808","convertedProductionTStamp":"2018-10-16T12:05:26.808","sentToBsdbTStamp":"2018-10-16T12:05:26.808","mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(WeatherStationSystem:MONITORED_SOFTWARE_SYSTEM)@(WeatherStationPlugin:PLUGIN)@(ConverterID:CONVERTER)@(WS-MeteoCentral-WindSpeed-Value:IASIO)","valueType":"DOUBLE"}
{"value":"-3.713","readFromMonSysTStamp":"2018-10-16T12:05:26.300","pluginProductionTStamp":"2018-10-16T12:05:26.755","sentToConverterTStamp":"2018-10-16T12:05:26.755","receivedFromPluginTStamp":"2018-10-16T12:05:26.808","convertedProductionTStamp":"2018-10-16T12:05:26.808","sentToBsdbTStamp":"2018-10-16T12:05:26.808","mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(WeatherStationSystem:MONITORED_SOFTWARE_SYSTEM)@(WeatherStationPlugin:PLUGIN)@(ConverterID:CONVERTER)@(WS-MeteoCentral-Temperature-Value:IASIO)","valueType":"DOUBLE"}
{"value":"7.527","readFromMonSysTStamp":"2018-10-16T12:05:26.300","pluginProductionTStamp":"2018-10-16T12:05:26.755","sentToConverterTStamp":"2018-10-16T12:05:26.755","receivedFromPluginTStamp":"2018-10-16T12:05:26.808","convertedProductionTStamp":"2018-10-16T12:05:26.809","sentToBsdbTStamp":"2018-10-16T12:05:26.809","mode":"OPERATIONAL","iasValidity":"RELIABLE","fullRunningId":"(WeatherStationSystem:MONITORED_SOFTWARE_SYSTEM)@(WeatherStationPlugin:PLUGIN)@(ConverterID:CONVERTER)@(WS-MeteoCentral-Humidity-Value:IASIO)","valueType":"DOUBLE"}
```

All the containers are up and running. The log of the `WebServerSender` shows exceptions:

```
2018-10-14T15:10:14.214 | ERROR [WebServerSender.java:295] [WebSocketClient@2136317607-164] Error on WebSocket connection
java.lang.IllegalStateException: WebSocketClient@1442405456 is not started
        at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:349)
        at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:324)
        at org.eso.ias.webserversender.WebServerSender.connect(WebServerSender.java:286)
        at org.eso.ias.webserversender.WebServerSender.connect(WebServerSender.java:290)
        at org.eso.ias.webserversender.WebServerSender.onClose(WebServerSender.java:213)
```

**Comment by sfehlandt** [comment]
Is this the log obtained by docker? "docker-compose ... logs" ? or a log file?

I downloaded all the log files and could not find the exception in them.
Also, did the process stop after that exception, that is, what you pasted here is the end of the log that you saw?

**Comment by acaproni** [comment]
It was in a log file. It might me the rolling deleted the file? Can you find the log file with the data of the 2018-10-14?
The docker container was still running and I did not shut it down.

Ale

**Comment by sfehlandt** [comment]
I am sorry I could find it after all.

First of all, it seems the code we are running is old, the lines of the WebServerSender.java file indicated in the exception do not match the code of the current commit in which the repo is positioned in the ias-server.

Anyhow, we believe this is a strange, random error that happens when the WebsocketClient has not finished starting when we try to connect:

`			client.start();
			client.connect(this, this.uri, new ClientUpgradeRequest());`

We tried to replicate the problem here but with no luck.
We propose to make the WebserverSender more robust, making it trying to reconnect whenever it fails connecting. That means to change the function `connect()` (see below) in order to make it run itself again in the catch of the Exception. Such implementation would prevent a problem like the one we had.

`public void connect() {
		try {
			sessionOpt = Optional.empty();
			this.connectionReady = new CountDownLatch(1);
			client = new WebSocketClient();
			client.start();
			client.connect(this, this.uri, new ClientUpgradeRequest());
			if(!this.connectionReady.await(reconnectionInterval, TimeUnit.SECONDS)) {
				logger.info("WebSocketSender could not establish the connection with the server.");
				logger.info("Trying to reconnect");
				connect();
			}
			logger.debug("Connection started!");
		}
		catch( Exception e) {
			logger.error("Error on WebSocket connection", e);
			this.shutdown();
		}
	}`

**Comment by acaproni** [comment]
Sebastian the solution you propose seems fine, please implement it.

The version running at the OSF is release 5 and  does not contain all the improvements in the sender that has been done after our duty trip at the OSF.
