### ISSUE TITLE
Improve operation mode and properties of the Multiplicity TF

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#153]
Actually the TF does not propagate the properties of the inputs to the output. 
[] propagate the properties of the inputs to the output: if 2 inputs have the same properties (keys) their values should be merged in the output
[] should it distinguish between the properties of the inputs that are set and the others?
[] should if distinguish between the properties of the operational inputs and the others?

The operational mode of the output is set to UNKNOWN if the mode of the inputs differ; otherwise it is set to their operational mode. There is no obvious way to set the mode of the output when the modes of the inputs differ.

**Comment by sfehlandt** [comment]
I disagree with this: "There is no obvious way to set the mode of the output when the modes of the inputs differ."

I think we could agree that the operation mode of an alarm that has some components in maintenance and some in operational modes should be set as operational. Or at least give the TF some way to configure this.

I suggest we think this practically, does it really make sense to have the Weather Stations global alarms (in the overview) in Unknown operational mode everytime there is at least 1 weather station in maintenance?

**Comment by acaproni** [comment]
This ticket is about the Multiplicity TF that is widely used in the field. The case of the weather station is just one case.

Each TF has full control over the output it produces, with the exception of the validity of course.
The multiplicity is generic so it does not know if it used for weather or for other purposes. We are, in fact, using the multiplicity many times. 
While for the validity or the priority there is a clear path forward, it is more difficult IMO to define a operational mode from the modes of the inputs that is also valid in general.
If we hide the operational mode, how can the IAS inform that operator that some of the WSs are not working properly? This would reduce their situational awareness. In an ideal world, there should be nothing not operational and if it is not operational needs to be fixed.

The case of weather station is somehow different because a WS can be shutdown on purpose if there are no antennas close to it. If the TF knows that inputs are shutdown it could take it into account while setting the mode of the output.
A change like the one that you propose seems to me more to be implemented in the ThresholdWithBackup or the BackupSelector TFs: those know the system and could mark the output operational even if some of the inputs are not operational and not needed to generate the output. 
This seems to me a much clearer solution to the problem.

**Comment by acaproni** [comment]
At the last weekly meeting we have decided that he mode of the multiplicity will depend on the mode of the inputs as it has always been.
The TF that has the knowledge of the meaning of the weather stations and their backups is the selector and we will improve it. 

In the scope of this ticket, we will improve the multiplicity to propagate the properties set in the inputs to the output.
As the alarm sate of the output comes from the alarm state of the inputs regardless of their mode, the multiplicity TF will propagate the properties of the inputs that are set regardless of their operational mode.
Other heuristics could be implemented in future if needed. In that case which heuristic to use could be selected by passing a java property.

**Comment by acaproni** [comment]
Actually, rethinking of the mode I preferred to calculate the mode of the output in this way
- depending on the mode of the inputs if it is cleared
- depending on the mode of the inputs that are SET if it is active

The rationale is that if the number of operational inputs that are also SET is enough to activate the output then the other inputs can be safely ignored.

If the output is SET, it will have
- the merged properties of the inputs that are SET
- a property with key `IdsOfAlarmsSet` with the IDs of the inputs that are SET.
If the output is cleared, it has no properties

**Comment by acaproni** [comment]
implemented
