### ISSUE TITLE
Alarms in MAINTENANCE mode should not be reported by email

### ISSUE THREAD

**Issue by csaldias** [IntegratedAlarmSystem-Group/ias#171]
It is our intention to put some alarms coming from problematic antenna subsystems into MAINTENANCE mode so that they don't appear in the IAS GUI. However, this doesn't prevent them to be reported via email which can be very annoying, especially if the problematic alarm is being triggered (and cleared) every few minutes.

Therefore, it is highly desirable that the email sender takes the operational mode of the alarm into consideration. That way, no email reports should be sent if an alarm is configured in MAINTENANCE mode.

We've previously discussed this with @acaproni and Johnny Reveco, and @acaproni suggested that the email sender should be updated to include this behavior.

**Comment by acaproni** [comment]
Implemented
