### ISSUE TITLE
CDB interface not pluggable

### ISSUE THREAD

**Issue by msekoranja** [IntegratedAlarmSystem-Group/ias#178]
Current implementation defines CdbReader as abstract interface and provides 2 implementations (JSON files and RDB). The selection of these 2 interfaces is hardcoded and it is not possible to "plug" any other CdbReader interface implementation.

**Comment by acaproni** [comment]
To be devloped in `feature/AllowThirdPartyCdbReader-Issue#178`bracnh.

**Comment by acaproni** [comment]
As Matej said, IAS has 2 CDB implementations

- RDB: based on hibernate (the URL of the database is in `hibernate.cfg.xml`)
- JSON: the path to the CDB folder is passed through the command line with the `-jcdb` parameter

IAS core tools use RDB by default unless the `-jcdb` parameter is set in the command line. This is done by an `if` in the  `main` of the tools like in the following snippet taken from the Supervisor:
```
val reader: CdbReader = {
      if (parsedArgs._2.isDefined) {
        val jsonCdbPath = parsedArgs._2.get
        Supervisor.logger.info("Using JSON CDB @ {}",jsonCdbPath)
        val cdbFiles: CdbFiles = new CdbJsonFiles(jsonCdbPath)
        new JsonReader(cdbFiles)
      } else {
        new RdbReader()
      }
    }
```

The purpose of this ticket is to be able use another implementation of the configuration, provided by the user.

This ticket should provide a `CdbReader` factory to be used by all the IAS core tools to ensure that the same stragey is used eveywhere. 
As we do not know if the user provided implementation needs parameters neither their type, it must be possible to instantiate the implementations with the default constructor and let it find their parameters by itself. This is already don by the RDB implemention that needs the URL of the database provided by the hibernate XML file. But the same pattern is not followed by the JSON implementation that expects the path of the CDB in the constructor.
One possible solution is to pass the path of the CDB with a java property or, alternatively, as a command line parameter.

**Comment by acaproni** [comment]
One solution that seems interesting is the [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) but it is not perfect unless we do some trick with introspection and/or define a ClassLoader to get user provided services from defined folders.
The pattern would be to use the user defined service if it exists in the folder, the JSON (eventually checking if the folder path has been passed as java property) and falling back to RDB is none of the other applies.

**Comment by msekoranja** [comment]
In order not to change current behaviour I would add additional command-line option, e.g.
`-cdb <class name>`
and simply instantiate class with introspection. The configuration of the loaded plugin is up to its implementation, i.e. usually JVM -D parameter and/or system env. variable.

**Comment by acaproni** [comment]
Yes Matej, with your proposal we introduce a backward incompatibility in the comamnd line of the tools and must allow to add jar to the IAS classpath (or give the possbility to extend the classpath with user defined folders).

**Comment by msekoranja** [comment]
For JSON and RDB I would leave the code as it is, but add option to load external implementations. No need for changing classpath.
For external implementation you need to. Adding support to add additional JARs to startup script is a backward compatible addition.

**Comment by acaproni** [comment]
The `ServiceLoader` needs a special set in the META-INF of the service to recognize and use the service. It seems more complicate than providing directly the class to load.

The new pattern for building the `CdbReader`  works in this way:
- if `-cdb cls` is in the command line, load the class (default empty constructor and parameters passed by java properties)
- else if `-jCdb path` is in the command line build and return the JSON reader
- else return the RDB reader (fallback)

An helper class, `CdbReaderFactory` instantiates and returns the `CdbReader` by following that policy.

The external implementation of the `CdbReader` must be provided in a jar file deploied in a folder whose pat must be set in the `IAS-EXTERNAL-JARS` environment variable. jars in this folder takes precedence over those in the IAS root folder (`lib` and `lib/ExtTools`)

**Comment by acaproni** [comment]
IMplements as described.
The following core tools have been updated to get the `CdbReader` with the factory:
- Converter
- CdbChecker
- IasMonitor
- NotificationSender
- Supervisor
- WebServerSender
