### ISSUE TITLE
CdbReader.init() is not being called

### ISSUE THREAD

**Issue by msekoranja** [IntegratedAlarmSystem-Group/ias#182]
Currently CdbReader.init() method is not being called by (all) IAS tools.
There is no clear documentation whether this needs to be explicitly called by the programmer, or should a CdbReader instance be (lazily) initialized automatically.

**Comment by msekoranja** [comment]
In addition CdbChecker does not call CdbReader.shutdown(). If the reader uses more complex implementation the process might not exit if shutdown() is not called.

**Comment by acaproni** [comment]
For the initialization I propose that the one that build the reader must call the setup and is also resonsible to close the reader.
That means that if the reader is passed in the constructor of an object, it must assume that it has been already initialized and must not close it when finished using the reader.
If, instead, an object builds the reader then it must also initialize and close.


I will update the documentation. Same logicfor the `CdbWriter`

**Comment by acaproni** [comment]
Fixed and commited in the develop branch.

IAS implementations of `CdbReader` and `CdbWriter` checks if the objects have been initialized and/or shutdown before accessing the CDB to help finding errors quickly.

**Comment by acaproni** [comment]
Fixed. The CdbChecker clearly reports the error.
Note that the CdbChecker reports the error (log at ERROR level) plus the exception
