### ISSUE TITLE
Improve Alarm implementation

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#4]
The actual implementation of a alarm (taken from the prototype) is not fully compliant with the requirements (@see [ALMA Memo 600](http://library.nrao.edu/public/memos/alma/memo600.pdf)):
- not all alarms can be shelved: key alarms require an authorization (so in principle they are shelved as well but not by everybody)
- an alarm can have different priorities ranging from warning to top priority (requirements do not specify how many priorities to implement but literature suggests 3, no more then 4)
- an alarm can have up to 4 different sounds associated  let operators to distinguish between new alarms
- link to documentation

**Comment by acaproni** [comment]
The min/default priority can be assigned in the CDB but must be possible to change (increase-only) programmatically.

**Comment by sfehlandt** [comment]
Besides the priority, this could be handled completely in the GUIs (Web Server + Displays). We can Add acknowledgement and shelving states, comments, etc to the CDB from the Web Server through a connector.

This way the Computing Elements from the Core will not need to deal with information that is not relevant for alarm processing, and that could imply a loss of performance.

**Comment by acaproni** [comment]
I guess the priority can be part of the computation if we want the transfer function to take priority into account.

**Comment by acaproni** [comment]
I agree with you Sebastian, some of those can be implemented in the web+display.

Priority:
- an alarm can be: set and cleared.
- an alarm has a priority assigned by default in the CDB or set to a default value
- the priority can be changed programmatically as we want the TF to be able to increase/decrease the priority of an alarm

Following the literature, the Alarm will have 4 possible priorities: LOW, MEDIUM, HIGH, CRITICAL.

Would that be enough to say that critical alarm cannot be shelved? This would simplify the implementation. This is a deviation from the requirements.

Initially I would set the priority to the default value of MEDIUM instead of setting in the CDB. This is again a simplification as it does not require support in the CDB. We can easily let the CDB assign a default priority but changing it would require a lot of intervention in the configuration unless we develop some supporting tool.

The sound and color of each priority is part of the web+display.
The link to the documentation should be added in the CDB.

**Comment by acaproni** [comment]
there is a wiki page describing the [deviation from the original requirements](https://github.com/IntegratedAlarmSystem-Group/ias/wiki/Deviations-from-requirement).

**Comment by acaproni** [comment]
E-ELT alarm system requirements states that there 3 possible priorities.

**Comment by acaproni** [comment]
The selective sheliving of alarms has been implemented in #79

**Comment by acaproni** [comment]
As of today, all the points described this old ticket have been implemented with the exception of priorities.
I prefer to close this ticket and follow up on priorities in #82
