### ISSUE TITLE
Test the JSON format of the messages sent by the WebServerSender

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias#51]
Currently, the WebServerSender sends the serialization of the IASValue using the IASValueJsonSerializer, and hence, the WebServer will expect JSONs in that format (with those fields)

In order to ensure that further changes to the serializer do not break this contract between the IAS Core and the IAS WebServer we should implement a test in the WebServerSender module that asserts the correct format.

**Comment by acaproni** [comment]
This test is not needed anymore because the WSS test gets JSON strings and converts them using already tested IAS core classes like the `IasValueJsonPojo` and the `IasValueStringSerializer`.
