### ISSUE TITLE
IasValues should have a "property" field

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias#53]
Currently there is no way to send the value that triggered an alarm along with the alarm in an IasAlarm (IasValue).

IasValue should have a new "property" field in order to include extra info. This should solve this problem, allowing to include the values in the field for any Alarm that requires it.

**Comment by acaproni** [comment]
Agreed, I would add a field with an array of properties in the form [key,value] (i.e. java properties basically).

In the same way, plugins should be able to associate array of properties to the values they send to the converters.
This task require to update plugins, converters, computing elements (to be able to read/set  properties in the TFs)

**Comment by acaproni** [comment]
Actually, plugin does not need to send additional properties so I would not add support there unless there is a clear use case.

**Comment by acaproni** [comment]
The change has been implemented in `add-Props-To-IASValue-Issue#53` branch.

The java and scala implementations of the `MinMaxThresholdTF` set the `actualValue` additional property to the value of the input that triggered/did not trigger the alarm.

**Comment by acaproni** [comment]
The JSON string published for the `IASValue`into the BSDB changed to somethign like:
```
{"value":"SET","pluginProductionTStamp":"1970-01-01T00:00:00.1","sentToConverterTStamp":"1970-01-01T00:00:00.2","receivedFromPluginTStamp":"1970-01-01T00:00:00.3","convertedProductionTStamp":"1970-01-01T00:00:00.4","sentToBsdbTStamp":"1970-01-01T00:00:00.5","readFromBsdbTStamp":"1970-01-01T00:00:00.6","dasuProductionTStamp":"1970-01-01T00:00:00.7","depsFullRunningIds":[],"props":{"key1":"value1","key2":"value2"},"mode":"DEGRADED","iasValidity":"RELIABLE","fullRunningId":"(Monitored-System-ID:MONITORED_SOFTWARE_SYSTEM)@(plugin-ID:PLUGIN)@(Converter-ID:CONVERTER)@(AlarmType-ID:IASIO)","valueType":"ALARM"}
```

The example shows 2 additional properties `key1` and `key2` with values `value1` and `value2` respectively.
Note that the `props` field is not present in the JSON string if there are no properties. The same happens with other parameters as well like the list of dependents and the timestamps.

**Comment by acaproni** [comment]
Merged to `develop`
