### ISSUE TITLE
Add logging to python scripts and modules

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#64]
Python scripts and module to log messages similarly to what java and scala do but in pythonic way.
Log files should be saved in `IAS_LOGS_FOLDER`.

**Comment by FaFilippo** [comment]
Create a file for the configuration of the logger inside Tools/src/python, now it's possible import this file and get the logger without implement it in every file.

**Comment by acaproni** [comment]
Filippo, is that using the standard python tool then?
We would like to have the logs in $IAS_ROOT/logs as for the java/scala tools. The name of the file and the format of the messages should be the same whenever possible: there could be differences between python and java/scala and in that case we want to stay in the python side.
In which branch are you developing the feature?

**Comment by FaFilippo** [comment]
Yes, i use the standard python logging.
For develop i use the brach feature/addLoggingPython-issue#64.
This is an example of the log:
```
2018-03-13 16:25:18,876 [MainThread  ] [INFO ]  start main
2018-03-13 16:25:18,899 [MainThread  ] [INFO ]  Set the temp folder for test /home/IASuserdev/IntegratedAlarmSystemRoot/tmp/ModuleForTest
```

Ok, i change the folder of the log, i will use  $IAS_ROOT like you suggest.

**Comment by acaproni** [comment]
Filippo, it looks good thank you.

For the timestamps of the messages we use ISO-8601 format that is very similar to what you just wrote:
```
2018-03-08T19:54:54.668 | INFO  org.eso.ias.kafkautils.SimpleStringConsumer | org.eso.ias.kafkautils.SimpleStringConsumer [SimpleStringConsumer.java:222] [main] Kafka consumer [SupervisorID] initialized
```

Is that possible to have ISO-8601 in the logs of python scripts?

For the name of the file we use n approach very close to what you propose. For the Supervisor the name of the log file is `Supervisor-SupervisorID-2018-03-08T19:54:53.724.log` where Supervisor-ID is the identifier of the Supervisor. For python scripts we do not have an identifier but I suggest to vaat lest the timestamps to distinguish between the logs of different instances of the script. So `iasRun.log` should be changed to `iasRun-2018-03-08T19:54:53.724.log`

I checked the branch but there is nothing (or I could not find). Did you push the changes you have locally in github?

**Comment by FaFilippo** [comment]
I don't know, let me check if i'ts possible and in that case i'll use it.

Ok, i change the name of the log file like those one,

Yes, i have push the new file yesterday and today, check if there are new
file in Tools/src/python.

Filippo.

2018-03-14 12:31 GMT+01:00 Alessandro Caproni <notifications@github.com>:

**Comment by acaproni** [comment]
Yes Filippo I found the file now.

Does the log write on both the file and the console?

Ideally, the Log file should be moved from Tools in the Logging module but then we should also swap the build order i.e. build Logging before Tools in `ias/build.xml`. We can think about that once you finish the implementation.

**Comment by FaFilippo** [comment]
In both, in the console and also in the file.
I try to run testCreateModule inside test and i see the log in console and
also in the new file created.

Yes, when i finish the test i move the python inside Logging module.


2018-03-14 13:22 GMT+01:00 Alessandro Caproni <notifications@github.com>:

**Comment by FaFilippo** [comment]
Hi Alessandro,

I made the request update:
* Now the filename is like the other name-date.log;
* The date inside the log is in ISO format because if the datefmt is not
set the ISO 8601 is used (source:
https://docs.python.org/3/library/logging.html?highlight=logging#logging.Formatter
).

Now i move te logConf in logging.

bye.
Filippo

2018-03-14 13:42 GMT+01:00 Filippo Fagioli <filippo.fagio@gmail.com>:

**Comment by acaproni** [comment]
If you move the file to Logging then you also have to change the build order to have Logging built before Tools. And check if there are broken dependencies: delete the content of the $IAS_ROOT and build the entire core.

Could you paste here one line of logs and the name of one of the files generated by the logging?

The format of the log messages for java/scala is in [logback.xml](https://github.com/IntegratedAlarmSystem-Group/ias/blob/develop/Logging/config/logback.xml):
* for the console: `<pattern>%d{HH-mm-ss.SSS, UTC} |%-5level| [%file:%line] [%thread] %msg%n</pattern>`
* for files: `<pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSS, UTC} | %-5level [%file:%line] [%thread] %msg%n</pattern>`
Check if it is possible for the python logging to follow the same patterns..

**Comment by FaFilippo** [comment]
The name of the file generated by the log are like this:
- testCreateModel2018-03-22T10:32:55.834242.log

For the log generated inside the file are composed like this:
- {2018-03-22 10:42:19,653 UTC} | INFO-5.5s | [testCreateModule.py 26] [MainThread:139895794902848] | Set the temp folder for test /home/IASuserdev/IntegratedAlarmSystemRoot/tmp/ModuleForTest

This is the console:
-{2018-03-22 10:42:19,653 UTC} | INFO-5.5s | [testCreateModule.py 26] [MainThread:139895794902848] | Set the temp folder for test /home/IASuserdev/IntegratedAlarmSystemRoot/tmp/ModuleForTest

I read inside the python documentation the only way for Logging to multiple destinations is use two logger (source: https://docs.python.org/3.0/library/logging.html?highlight=logging#logging-to-multiple-destinations) so or we use two logger and it's possible set different format or we use only one with the same format in both.

**Comment by acaproni** [comment]
Filippo thank you for your investigation. I would keep one logger with the same format for file and console.

From where does the file name come from? Is it the name of the python executable? 

I would say that the name of the log file is also ok. It would be optimal to limit the time to millisecondsi.e. only 3 digits after the dot: testCreateModel2018-03-22T10:32:55.xxx.log as this is what we do for java/scala.

**Comment by acaproni** [comment]
Let me understand better Filippo. What happens if file1.py invoke methods of file2.py and both log messages?

**Comment by acaproni** [comment]
No this is not what we want. We must have only one log file with the name of the python script we launched. In my example, only one log file named test1....log where logs of both scripts go.

The reason is that if we are looking at the logs for debugging we want to have all of them in the same place (file) instead of jumping from one file to another. Think of a case where we have many source files interacting... It can seem a silly detail right now but it will become very important as soon as we will start developing python GUIs for example.

**Comment by FaFilippo** [comment]
Is writed in the file created from the root, in this case test1data.log

**Comment by acaproni** [comment]
Perfect, just wanted to be sure. Thank you, Filippo.

**Comment by FaFilippo** [comment]
Like this:
{2018-03-22 13:53:42,765, UTC} | INFO | [printElem.py 5] [MainThread:140243629971264] | this is a test
{2018-03-22 13:53:42,778, UTC} | INFO | [testCreateModule.py 27] [MainThread:140243629971264] | Set the temp folder for test /home/IASuserdev/IntegratedAlarmSystemRoot/tmp/ModuleForTest

**Comment by acaproni** [comment]
Is it possible to format so that we have 
```2018-03-22T13:53:42,765 | INFO | [printElem.py:5] [MainThread:140243629971264] | this is a test```
instead of 
```{2018-03-22 13:53:42,765, UTC} | INFO | [printElem.py 5] [MainThread:140243629971264] | this is a test```

What is the big number 140243629971264?

**Comment by FaFilippo** [comment]
The id of the thread, i forgot to remove it! 

Yes, it's possible!

**Comment by FaFilippo** [comment]
Now we have this format for the log inside the file:

- 2018-03-22 14:18:55.110  | INFO | [testCreateModule.py 70] [MainThread] | start main

and this for the console:

- 14:18:55.110 INFO     [testCreateModule.py 70] start main

**Comment by acaproni** [comment]
Great! Thank you Filippo

**Comment by FaFilippo** [comment]
I'm going to move logConf from Tools into Logging, improve .project with pythonNature and add pydevproject.

**Comment by acaproni** [comment]
Yes thank you. Remober to check dependencies. I suggest you to remove the content IAS_ROOT and rebuild the entire IAS from scratch to double check.

**Comment by acaproni** [comment]
Filippo, the build of the branch immediately fail:
```/home/acaproni/ias/Logging/src/build.xml:6: Cannot find /home/acaproni/IasRoot/config/CommonAnt.xml imported from /home/acaproni/ias/Logging/src/build.xml```

This is because `CommonAnt.xml` is installed by `Tools` so `Logging` cannot be built before `Tools`.

After some time I have lost some details that cannot find in the comment of the ticket.
We said to move logConf from Tools into Logging but then the order of the build has been moved putting Logging before Tools. I rememebr we discussed about that but cannot remember why...

**Comment by acaproni** [comment]
Ok, I think I have recollected the information.
The reason to move Logging before Tools is because python scripts in Tools needs it. Isn´t it?

**Comment by FaFilippo** [comment]
Hi Alessandro!
Yes this this is why we move Logging before Tools, the python script like IASrun use logConf file for the logging configuration. 
If we install Tools after Logging?

**Comment by acaproni** [comment]
We can´t install Tools after Logging because of a dependency with [`CommonAnt.xml`](https://github.com/IntegratedAlarmSystem-Group/ias/blob/develop/Tools/config/CommonAnt.xml).

To see the error, make
1 remove the the ias root `rm -rf $IAS_ROOT/*`
1 ant build

We could
* move stuff in the  `Logging` module into `Tools`
* split `Tools` in 2 parts where to install `CommonAnt.xml` befor Logging
* create a new module for python stuff
* ...

**Comment by acaproni** [comment]
Filippo please change the name of the python package in `Logging` from IASTools to something like `IASLogging`. You might need to rename the python files that refer to the `Log` class

**Comment by acaproni** [comment]
I propose this solution:
1. ant build starts with `Tools` 
1. Create a new `Utils` module
1. Move everything from `Logging` into `Utils`
1. remove `Logging`
1. move scala and python executables from `Tools` to `Utils`, including the test

There are also external packages in `Tools/extTools` and `Logging/extTools`. Filippo please check in which module we have top move them.

Does it sounds a good solution?

**Comment by FaFilippo** [comment]
For me it's ok, i try your solution right now and i'm going to upload it.

I also try to move the external package from Utils to Tools but when i
install the module Utils the build failed. I leave the external module like
i found it in Logging.



2018-04-18 16:12 GMT+02:00 Alessandro Caproni <notifications@github.com>:

**Comment by acaproni** [comment]
Merged in the develop branch. Build and tests pass on jenkins.

I close the ticket now, thank you Filippo.
