### ISSUE TITLE
The property to define kafka servers specified in the arguments of iasRun are not being used by the converter

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias#67]
When we run the converter with the iasRun and the argument to specify the kafka servers, the converter continue using the default server "localhost:9092".
The command that we are using is:

`$ iasRun -l s -Dorg.eso.ias.converter.kafka.servers=IP:9092 org.eso.ias.converter.Converter ConverterID -jcdb CDB_FOLDER`

We think that it is probably because in the line 224 in the org.eso.ias.converter.Converter the converter
is being initialized with a new Properties() instead of the properties received in the arguments.

`ConverterStream converterStream = context.getBean(ConverterStream.class,id, new Properties());`

**Comment by acaproni** [comment]
What properties do you refer to? java properties?

**Comment by jmaldonadof** [comment]
When we run the converter with the iasRun and the argument to specify the kafka servers, the converter continue using the default server "localhost:9092". 
The command that we are using is:

`$ iasRun -l s -Dorg.eso.ias.converter.kafka.servers=<ip>:9092 org.eso.ias.converter.Converter ConverterID -jcdb <cdb-folder>`

We think that it is probably because in the line 224 in the org.eso.ias.converter.Converter the converter 
is being initialized with a new Properties() instead of the properties received in the arguments.

`ConverterStream converterStream = context.getBean(ConverterStream.class,id, new Properties());
`

**Comment by jmaldonadof** [comment]
Yes, the java property to specify the kafka servers.

**Comment by acaproni** [comment]
Yes, i think you are right Jazmine.
Do you have time to test if passing System properties fixes the issue?

Now that I saw your command line, I realized that `iasConverter` (that you are not using) does not cope with java properties.

in fact a command like 
```iasConverter -Dorg.eso.ias.converter.kafka.servers=<ip>:9092 ConverterID -jcdb <cdb-folder>```
woudl send the string `-Dorg.eso.ias.converter.kafka.servers=<ip>:9092` as a param to the converter instead of setting a java property.

**Comment by jmaldonadof** [comment]
Yes, we change the line 224 passing it the System properties and the problem was solved.

`ConverterStream converterStream = context.getBean(ConverterStream.class,id, System.getProperties());`

Sebastian will correct it now in the develop branch.

**Comment by acaproni** [comment]
Great! Thank you!
