### ISSUE TITLE
There should be a property to define kafka servers specified in the arguments of iasRun in order to run the WebserverSender

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias#69]
When we run the WebserverSender with the iasRun there should be an argument to specify the kafka servers, to change the default server "localhost:9092".

The command should be something like this:

$ iasRun -l s -Dorg.eso.ias.[property]=IP:9092 org.eso.ias.converter.Converter ConverterID -jcdb CDB_FOLDER

Were [property] should be the property. We know for sure this is not implemented.
It should be implemented because the Converter, Supervidor, etc are meant to work this way.

See issues [#67](https://github.com/IntegratedAlarmSystem-Group/ias/issues/67) and [#68](https://github.com/IntegratedAlarmSystem-Group/ias/issues/68)

**Comment by jmaldonadof** [comment]
Closed with the commit 6445e8d43d02d10981cd46bb021e0c5b73273a06
