### ISSUE TITLE
Plugin KafkaPublisher has a System.out.println that breaks the DummyPlugin

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias#76]
Line 109 of file ias/plugin/src/java/org/eso/ias/plugin/publisher/impl/KafkaPublisher.java says the following:
System.out.println("jsonStrToSend "+jsonStrToSend);

When we compile the DummyPlugin with this change it starts printing and that breaks the usage of the DummyPlugin as the instructions we write  through the command line get mixed up with the printing, making it unusable.

**Comment by acaproni** [comment]
The println has been added by Filippo probably while implementing [#48](https://github.com/IntegratedAlarmSystem-Group/ias/issues/48)
