### ISSUE TITLE
CDB to allow configuration of identical equipments by means of templates

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#80]
REQ-FUNC-012:
_This is needed in order to ease the configuration of the system. There shouldn’t be the need for example to individually define all antennas, but it should be possible to use as template the configuration of the elements for one antenna to define another one_

**Comment by acaproni** [comment]
This requirement must be reformulated as the core, where the CDB resides, is agnostic of specifics of the monitored systems.
What we need from the CDB is to be able to replicate the monitoring of devices that means running the same set of supervisors against the same set of inputs.

As a simple case of replicated devices, think of the identical weather stations. For implementing this requirement
* we must be able to define the inputs and the supervisors (with their DASUs and ASCEs) needed to monitor and generate the alarms for only one weather station: this is the template
* be able to map the template to the n real instances (n weather stations in our example)

**Comment by acaproni** [comment]
We need to introduce an additional table, TEMPLATE, with a unique ID and 2 numeric fields: min and max.
The concept is that we want to add the identifier of the template to the name of the Supervisor and let the CDB automatically generate  identical copies of such Supervisor.
For example 
1. the TEMPLATE table contains a row with `[ID=Template1, min=1, max=3]` 
1. A supervisor with unique `Id=WeatherStationSuperv%Template1%`
1. the CDB will create 3 identical supervisors with IDs=`WeatherStationSuperv1`, `WeatherStationSuperv2` and `WeatherStationSuperv3`.
1. at the same way, the CDB will also generate a set of IASIOs (the inputs and outputs of the DASUs/ASCEs running in the supervisor

| Name | Type |
| ------------ | -------|
|  template_id | String |
|  min | Integer>=0 |
| max | Integer>min |

Instead of having the name of the template in the name of the supervisor we could add an additional column, `tempalte_id` to the Supervisor table so that, if present, the CDB generate identical copies of that Supervisor. In the same way, we could add an optional field to the IASIO table.

From the template ID and the Supervisor ID, the CDB generates all other items: inputs IDs, output IDs, DASU and ASCE IDs.

**Comment by acaproni** [comment]
Comparison between the 2 proposed methods:

* Method 1: _add the reference to the template in the ID of the Supervisor and other items_
  * Pros
    * Immediately visible that an ID is generated out of a template
  * Cons
    * The name pattern of IDs is decided by the user as it depends on the position of the reference to the ID of the template
     * exposes the pattern and special characters to the user editing the CDB (it can be mitigated by providing dedicated GUIs)
    * error prone (for example a typo in the string used to reference the template in the ID of the Supervisor)

* Method 2: _add an additional (with an optional value) column to the Supervisor and other items_
  * Pros
    * Details of template totally under control of the core of the IAS
    * the database can help to maintain consistency i.e. less error prone
    * the  link to the template is easier to find
  * Cons
    * Require more changes in the database and possibly more changes in the sources

Considering the table, i would go for the implementation with the latter method.

**Comment by acaproni** [comment]
While implementing this ticket, I also fixed #34 that introduces a backward compatibility issue in JSON CDB.
Look at #34 for further details.

**Comment by acaproni** [comment]
While implementing this ticket, I also fixed #79  that introduces a backward compatibility the RDB CDB.
Look at #79 for further details.

**Comment by acaproni** [comment]
At first glance we need to add a `template_id` foreing key to the Supervisor, its inputs and outputs.
The CDB shall then be able to reproduce the entire supervisor and replicate its behavior between `[nim,max]` different instances,

For implementing this functionality in the CDB we shall not extend the JSON and RDB implementations but provide a CDB reader on top of them that generates the replicated instances on the fly, based on the underlying CDB configuration. It means that the original JSON and RDB readers only get raw data delegating the replication to a new reader.

**Comment by acaproni** [comment]
As discussed at the meeting, there is a problem in the RDB implementation while JSON CDB works well.

Replication is implemented through template entries: if an element is replicated then it contains a reference to a row in template. If the element is not replicated then the foreign key is null.
Below the case of a replicated IASIO. it has a `template_id` foreign key that is NULL (not replicated) or points to a row of the template table:

```
CREATE TABLE TEMPLATE (
  template_id VARCHAR2(64) NOT NULL,
  min NUMBER(8) NOT NULL CHECK (min>=0),
  max NUMBER(8) NOT NULL CHECK (max>0),
  CONSTRAINT maxGreaterThenMin CHECK (max>min),
  CONSTRAINT TEMPLATE_PK PRIMARY KEY(template_id));

CREATE TABLE IASIO (
  io_id varchar2(64) NOT NULL,
  shortDesc VARCHAR2(256),
  iasType VARCHAR2(16) NOT NULL,
  docUrl VARCHAR2(256),
  canShelve NUMBER(1), -- boolean 0/1
  template_id VARCHAR2(64),
  FOREIGN KEY(template_id) REFERENCES TEMPLATE(template_id),
  CONSTRAINT IASIO_PK PRIMARY KEY(io_id));
```

The error returned by the tests is a failure inserting a IASIO without replication (i.e. IASIO.template_id=NULL):
`ORA-02291: integrity constraint (IASTEST.SYS_C00183967) violated - parent key not found`

Any idea?

**Comment by jmaldonadof** [comment]
I think that if you add explicitly that the  template_id could be NULL the constraint violation error should disappear 

```
CREATE TABLE IASIO (
  io_id varchar2(64) NOT NULL,
  shortDesc VARCHAR2(256),
  iasType VARCHAR2(16) NOT NULL,
  docUrl VARCHAR2(256),
  canShelve NUMBER(1), -- boolean 0/1
  template_id VARCHAR2(64) NULL,
  FOREIGN KEY(template_id) REFERENCES TEMPLATE(template_id),
  CONSTRAINT IASIO_PK PRIMARY KEY(io_id));
```

**Comment by jmaldonadof** [comment]
I see. Do you have the java code?
Maybe for some reason the mapping is considering the template_id as empty instead of Null, because it is a varchar. It is only an idea.

**Comment by acaproni** [comment]
I have found the problem. It was in the test actually: I was inserting a record with a not null foreign key that was not in the TEMPLATE. My mistake (what a shame!).
Thank you, Jazmine.

**Comment by acaproni** [comment]
At the present, the Supervisor expects to get its ID from the command line. Such ID is used 
* to get the configuration from the CDB
* to write the ID in the name of the log file

For templated supervisors we must change the command line to pass the number of the instance to run i.e. if we want to start the n-th replica of the supervisor with ID id then the command line must be  something like ```iasSupervisor ID -instance=n```.
The CDD reader 
1. accesses the SUPERVISOR table with the unique key ID
1. gets the ID of the template from the supervisor read in the previous step
1. gets the template and ensure that _template.min&lt;=n&lt;=template.max_
1. builds the ID of the Supervisor to use at run time (for example `ID-1`)
1. gets the IASIOs (inputs and outputs) with the same strategy used for the supervisor ID

As already said at the beginning, plugins are not affected by this change: they are expected to produce the monitor points with the proper names. It is always possible to replicate a plugin, so we should better provide a tool to produce the ID of replicated IASIOs for the benefit of the plugins when.

**Comment by acaproni** [comment]
Just realized that TFs cannot be agnostic of replication. 
The case described upon, i.e. a instance i of a replicated DASU i that has a replicated set of the very same inputs and produces an output i is very a particular case. 

More in general, the inputs of a replicated or not replicated DASU can be:
* a simple monitor point value or alarm produced by a plugin, that we already have
* a monitor point value or alarm generated by a plugin with replication, that we will support in #81 
* a synthetic parameter or alarm generated by a non replicated DASU, that we already have
* a synthetic parameter or alarm generated by a replicated DASU

We want that the same naming pattern is followed all along the IAS i.e. by values generated by plugins and those produced by the DASUs.

The TF must know the number of the replica, passed to the Supervisor by means of a command line parameter or a java property. 
The map of inputs passed to the TF must allow to get parameters by their ID, or by their base ID+number of replica. 
More in general, each identifier of a value can be thought to be composed of the base ID plus an optional replication number. The replication number is defined only for replicated items.

**Comment by acaproni** [comment]
The Supervisor is the deployment unit of DASUs. What we want to replicate are the DASUs not the Supervisors so we should move the template_id from the Supervisor to DASUs and ASCEs and improve the Supervisor to distinguish between replicated and normal DASUs to run. In this way, it is possible to run in a given Supervisor normal DASUs, different selected instances of the same replicated DASU or instances of other replicated DASUs at the same time.

The case described in the past days of a templated Supervisor could be implemented later if needed to ease the deployment but with limitations like for example being able to run only one templated  DASUs with the same instance of the Supervisor itself.  For this reason I will not implement templated Supervisosr.

**Comment by acaproni** [comment]
The Supervisor is the deployment unit of DASUs. What we want to replicate are the DASUs not the Supervisors so we should move the template_id from the Supervisor to DASUs and ASCEs and improve the Supervisor to distinguish between replicated and normal DASUs to run. In this way, it is possible to run in a given Supervisor normal DASUs, different selected instances of the same replicated DASU or instances of other replicated DASUs at the same time.

The case described in the past days of a templated Supervisor could be implemented later if needed to ease the deployment but with limitations like for example being able to run only one templated  DASUs with the same instance of the Supervisor itself.  For this reason I will not implement templated Supervisosr.

**Comment by acaproni** [comment]
The ASCE, DASU and IASIOs DAOs read from the CDB can or cannot be templated that means that they contain the identifier of the template and the number of the instance.
The CDB return the DAO as they are in the database without further manipulation.
It is the Supervisor that converts (normalizes) the templated data structures into stabndard DAOs.

The conversion basically means to replace the identifiers of IasioDaos, AsceDaos and DasuDaos with the instance number as described in my previous comment.

Constraints:
- if a DASU is templated then the same template applies to its ASCEs and output. The inputs of a DASU can or cannot be templated but if they are templated then their templates matche with that of the DASU.
- the output of  templated ASCE is templated, for its IASIOs in input the same rule of the DASU applies; the output of a ASCE is always templated

The conversion is done by [TemplateHelper](https://github.com/IntegratedAlarmSystem-Group/ias/blob/feature/template-cdb-configuration-Issue%2380/Supervisor/src/scala/org/eso/ias/supervisor/TemplateHelper.scala) that also checks if all the constraints have been respected.

**Comment by acaproni** [comment]
We have added methods to the ASCEs, the DASUs and the [TransferExecutor](https://github.com/IntegratedAlarmSystem-Group/ias/blob/develop/CompElement/src/java/org/eso/ias/asce/transfer/TransferExecutor.java) returning the number of the instance of a templated item.

The implementators of the TF should not care of the number of the instance and never deal with such method. If it is not the case, the implementations are violating the constraint that all the copies are the same and indistinguishable. 

The `eval` method of the TF receives a map of values that the implementation get trough their IDs. 
This works well if there are no templates because the IDs is well known.

If the TF runs on a templated ASCE, the ID of the inputs can be templated or not. For the templated inputs, the real ID is build by the Supervisor and unknow to the implementer of the TF when they write it. The real ID of a templated IASIOs is ultimately built from the generic ID plus a string as described upon.
To avoid the user to deal with the pattern (that can also change in future) and with internal API to build a concrete ID out of the template and the number of the instance, we the java and scala transfer executor provide a `getValue` that does all the magic.
`getValue` returns a value from its ID independently if it is templated or not and independently of the particular instance number.

**Comment by acaproni** [comment]
Implemented and merged in `develop`. 

Documentation will be provided in the wiki.
